framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            pealim_parse:
                dsn: '%env(PEALIM_PARSE_TRANSPORT_DSN)%'
                options:
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\TestMessage: async
            App\Message\PealimParse: pealim_parse

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
